/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_incomplete_trainingtest_NDKJniUtiles */

#ifndef _Included_com_example_incomplete_trainingtest_NDKJniUtiles
#define _Included_com_example_incomplete_trainingtest_NDKJniUtiles
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_incomplete_trainingtest_NDKJniUtiles
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_incomplete_trainingtest_NDKJniUtiles_getJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
